name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: vuepress-deploy
      uses: guanchao/workflow-engine-book@main
      env:
        ACCESS_TOKEN: ${{ secrets.WORKFLOW_ENGINE_BOOK }}
        TARGET_REPO: guanchao/workflow-engine-book
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn docs:build
        BUILD_DIR: docs/.vuepress/dist
